FROM bitnami/spark:3.4.1

USER root

# Install python packages required for spark jobs
RUN pip install delta-spark==2.4.0 confluent-kafka==2.1.1 great-expectations==0.17.15 mlflow==2.7.1

# Download S3 & Delta Lake connector jars
ADD https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar /opt/bitnami/spark/jars/
ADD https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar /opt/bitnami/spark/jars/
ADD https://repo1.maven.org/maven2/io/delta/delta-core_2.12/2.4.0/delta-core_2.12-2.4.0.jar /opt/bitnami/spark/jars/
ADD https://repo1.maven.org/maven2/io/delta/delta-storage/2.4.0/delta-storage-2.4.0.jar /opt/bitnami/spark/jars/

USER 1001
